### ISSUE TITLE
ideias

### ISSUE THREAD

**Issue by yanmarques** [yanmarques/software-engineering-work#1]
Devemos discutir aqui as ideias para o projeto.

**Comment by yanmarques** [comment]
Para o (possível) deploy ou teste em produção, é possível usarmos uma darknet/rede anônima que possua o recurso _hidden services_.

Prós:
- possibilidade de usar nossa máquina como servidor, dando acesso a todas as funcionalidades disponíveis, sendo que se usassemos um hoster grátis teríamos certas limitações
- sem login/cadastro em hosters
- downtime depende somente dos devs
-  possibilidade de limitar o acesso (para testes por exemplo)
- qualquer pessoa no mundo, indepedente da sua região, sistema político, deve ter acesso

Contras:
- downtime depende somente dos devs, logo para mantermos o serviço em pé ao menos um dos devs devem estar up
- uso de um software específico para o acesso
- overhead no acesso, causando lentidão 
- pode ser bloqueado em alguns países com regime ditatorial
- configurar o ambiente; instalar as dependências do projeto; configurar servidor de aplicação e o servidor web; manter o ambiente atualizado

**Comment by kawaiicaretaker** [comment]
Desenvolvimento de um jogo para pessoas com deficiência visual em plataforma mobile

Prós:

- Imersão de pessoas com deficiencia ao mundo dos games.

Contras:

- A maior parte do game vai ser sem nenhum visual grafico, somente som.
- Dificuldade em achar materiais sonoros para efeitos e dialogo de personagems.
- Tempo para o desenvolvimento muito curto.

**Comment by yanmarques** [comment]
Com as últimas discussões, foram estabelecidos detalhes sobre que plataformas, tecnologias e ambientes o jogo estará disponível. Tentarei colocar em tópicos aquilo que foi conversado (posso ter esquecido de alguma coisa):
- Unity para o desenvolvimento do jogo (em c#)
- desktop e/ou mobile ou colocar na steam
- web é ainda uma dúvida, pois não funciona nos navegadores mobile
- ambientação deve ser de ótima qualidade, afinal será a maior parte do jogo logo é preciso fazer testes com diferentes aplicações
